spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserService
    username: postgres
    password: 2004
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379