spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/UserService
    username: user_service_user
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml


  data:
    redis:
      host: redis
      port: 6379